# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b7dddfb15bebcff514bca4d6e99f6ae8aa3d0a413294f67139a185ce975ad938d797159a999e0e329111c7925d0bec2487e40b2fe9ea8e827d666ea03dddbe0

test:
  secret_key_base: cc73983b2d0674f81c2ad436bc53811905898985042edb1ece129b825e7ae8551557ecf102d55ace78512acb8f12d129787f3878f1e0ea0fa2fb4a4520c65f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
